gate:
    host: "https://api.gateio.ws/" 
    prefix: "api/v4"
    apiKey: "placeholder"
    gate-endpoints:
      wallet: "/wallet"
      spot: "/spot"
      margin: "/margin"
stex:
    host: "https://api3.stex.com"
    prefix: ""
    apiKey: "placeholder"
    stex-endpoints:
      public: "/public"
      trading: "/trading"

